"""
One-shot retrofit gate for cio-letter-prep.

Compares two .docx files produced by the cio-letter-prep skill — typically a
post-retrofit candidate and the baseline `fixtures/golden_pack_2026-04.docx` —
and asserts they are visually identical at the level the retrofit could
silently break:

  (a) document.styles font names for Heading 1/2/3 + Body Text
  (b) palette hex values in word/theme/theme1.xml
  (c) cover-page header image presence + width-EMU within ±5% tolerance
  (d) section count + table row counts (existing weaker check, retained)

Usage:
    python compare_docx.py <candidate.docx> <golden.docx>

Exit codes:
    0 — PASS (no diff)
    1 — FAIL (one or more property diverges)

Runs as a one-shot gate after the cio-letter-prep retrofit lands.
Not a CI test — the skill's output cannot be generated by pytest because
cio-letter-prep is an LLM-driven Claude skill. The script is the automated
half of a manual procedure documented in SKILL.md.
"""

from __future__ import annotations

import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LOGO_WIDTH_TOLERANCE = 0.05  # ±5% of EMU width
HEX_PATTERN = re.compile(r"#?[0-9A-Fa-f]{6}\b")
HEADING_STYLES = ("Heading 1", "Heading 2", "Heading 3", "Body Text")


# ---------------------------------------------------------------------------
# Extractors
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DocxSnapshot:
    fonts: dict[str, str | None]
    palette_hex: list[str]
    logo_count: int
    logo_width_emu: int | None
    section_count: int
    table_row_counts: tuple[int, ...]


def _font_for_style(doc: Document, style_name: str) -> str | None:
    """Return the font name set on a style, or None if the style is absent."""
    try:
        style = doc.styles[style_name]
    except KeyError:
        return None
    if style.font is None:
        return None
    return style.font.name


def _extract_palette_hex(docx_path: Path) -> list[str]:
    """Pull all hex color tokens from theme1.xml, in document order."""
    with zipfile.ZipFile(docx_path) as z:
        if "word/theme/theme1.xml" not in z.namelist():
            return []
        theme_xml = z.read("word/theme/theme1.xml").decode("utf-8")
    hexes = HEX_PATTERN.findall(theme_xml)
    return [h.lstrip("#").upper() for h in hexes]


def _extract_header_logo(doc: Document) -> tuple[int, int | None]:
    """Return (logo_count, first_logo_width_emu_or_None) across header parts.

    cio-letter-prep inserts the cover-page logo as a Word header part image
    (the `docx` skill chain convention for cover-page assets). We count inline
    shapes in `header`, `first_page_header`, and `even_page_header` of the
    first section. If a future docx-skill revision relocates the logo to a
    body paragraph (e.g., `document.xml` rather than `header*.xml`), both
    candidate and golden will report 0 logos here and the check will silently
    pass — extend this function in that case.
    """
    if not doc.sections:
        return 0, None
    section = doc.sections[0]
    count = 0
    width_emu: int | None = None
    for header in (section.header, section.first_page_header, section.even_page_header):
        if header is None:
            continue
        for shape in header.part.element.iter(qn("w:drawing")):
            count += 1
            if width_emu is None:
                ext = shape.find(f".//{qn('a:ext')}")
                if ext is not None:
                    cx = ext.get("cx")
                    if cx and cx.isdigit():
                        width_emu = int(cx)
    return count, width_emu


def snapshot(docx_path: Path) -> DocxSnapshot:
    doc = Document(str(docx_path))
    logo_count, logo_width = _extract_header_logo(doc)
    return DocxSnapshot(
        fonts={s: _font_for_style(doc, s) for s in HEADING_STYLES},
        palette_hex=_extract_palette_hex(docx_path),
        logo_count=logo_count,
        logo_width_emu=logo_width,
        section_count=len(doc.sections),
        table_row_counts=tuple(len(t.rows) for t in doc.tables),
    )


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------


def compare(candidate: DocxSnapshot, golden: DocxSnapshot) -> list[str]:
    """Return list of diff strings; empty list = PASS."""
    diffs: list[str] = []

    # (a) fonts
    for style, golden_font in golden.fonts.items():
        cand_font = candidate.fonts.get(style)
        if cand_font != golden_font:
            diffs.append(
                f"FONT[{style}]: candidate={cand_font!r} golden={golden_font!r}"
            )

    # (b) palette hex (order-sensitive: theme.xml token positions matter)
    if candidate.palette_hex != golden.palette_hex:
        # Show the first divergence for actionable output
        for i, (c, g) in enumerate(zip(candidate.palette_hex, golden.palette_hex)):
            if c != g:
                diffs.append(
                    f"PALETTE[token {i}]: candidate=#{c} golden=#{g} "
                    f"(token count: candidate={len(candidate.palette_hex)} "
                    f"golden={len(golden.palette_hex)})"
                )
                break
        else:
            diffs.append(
                f"PALETTE length: candidate={len(candidate.palette_hex)} "
                f"golden={len(golden.palette_hex)}"
            )

    # (c) logo presence + width
    if candidate.logo_count != golden.logo_count:
        diffs.append(
            f"LOGO count: candidate={candidate.logo_count} golden={golden.logo_count}"
        )
    elif golden.logo_width_emu is not None and candidate.logo_width_emu is not None:
        delta = abs(candidate.logo_width_emu - golden.logo_width_emu)
        if delta > golden.logo_width_emu * LOGO_WIDTH_TOLERANCE:
            pct = 100 * delta / golden.logo_width_emu
            diffs.append(
                f"LOGO width: candidate={candidate.logo_width_emu} "
                f"golden={golden.logo_width_emu} "
                f"({pct:.1f}% diff > {LOGO_WIDTH_TOLERANCE * 100:.0f}% tolerance)"
            )

    # (d) section + table structure (weaker check, retained from prior contract)
    if candidate.section_count != golden.section_count:
        diffs.append(
            f"SECTIONS: candidate={candidate.section_count} golden={golden.section_count}"
        )
    if candidate.table_row_counts != golden.table_row_counts:
        diffs.append(
            f"TABLE ROWS: candidate={candidate.table_row_counts} "
            f"golden={golden.table_row_counts}"
        )

    return diffs


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    candidate_path = Path(argv[1])
    golden_path = Path(argv[2])

    for label, path in (("candidate", candidate_path), ("golden", golden_path)):
        if not path.is_file():
            print(f"ERROR: {label} not found: {path}", file=sys.stderr)
            return 2

    candidate = snapshot(candidate_path)
    golden = snapshot(golden_path)
    diffs = compare(candidate, golden)

    if not diffs:
        print(
            "PASS — fonts, palette, logo properties, sections, and table rows "
            "identical between candidate and golden."
        )
        return 0

    print(f"FAIL — {len(diffs)} divergence{'s' if len(diffs) != 1 else ''}:")
    for d in diffs:
        print(f"  {d}")
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
